-- Run this once in the Supabase SQL Editor for project sagjxhxtkqtbzzhudggj.
-- Backs the new Machining Hours screen and finishes the "Machining Hours"
-- report, which was previously a stub in report-data.server.ts.

create table if not exists public.machine_hours (
  id integer primary key generated by default as identity,
  machine_id integer references public.machines (id) on delete set null,
  operator_id integer references public.app_users (id) on delete set null,
  work_date date not null,
  hours numeric not null default 0,
  job_number text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.machine_hours enable row level security;

drop policy if exists "authenticated full access" on public.machine_hours;
create policy "authenticated full access" on public.machine_hours
  for all to authenticated using (true) with check (true);
