-- Run this once in the Supabase SQL Editor for project sagjxhxtkqtbzzhudggj.
-- Stores each signed-in user's browser push subscription so the server can
-- send real low-stock notifications (see src/lib/push/send-push.server.ts),
-- replacing the frontend-only toast that used to be the only delivery.

create table if not exists public.push_subscriptions (
  id integer primary key generated by default as identity,
  user_id uuid not null references auth.users (id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "users manage their own subscription" on public.push_subscriptions;
create policy "users manage their own subscription" on public.push_subscriptions
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
