-- Run this once in the Supabase SQL Editor for project sagjxhxtkqtbzzhudggj,
-- after data_migration.sql. Adds report generation + storage for the
-- Timeliness Configuration feature.

create table if not exists public.generated_reports (
  id integer primary key generated by default as identity,
  configuration_id integer,
  report_table text not null,
  period_start date not null,
  period_end date not null,
  storage_path text not null,
  file_name text not null,
  row_count integer not null default 0,
  created_at timestamptz default now()
);

alter table public.generated_reports enable row level security;

drop policy if exists "authenticated full access" on public.generated_reports;
create policy "authenticated full access" on public.generated_reports
  for all to authenticated using (true) with check (true);

-- Private bucket for the generated PDFs (downloaded via short-lived signed URLs).
insert into storage.buckets (id, name, public)
values ('reports', 'reports', false)
on conflict (id) do nothing;

drop policy if exists "authenticated read reports" on storage.objects;
create policy "authenticated read reports" on storage.objects
  for select to authenticated using (bucket_id = 'reports');

drop policy if exists "authenticated write reports" on storage.objects;
create policy "authenticated write reports" on storage.objects
  for insert to authenticated with check (bucket_id = 'reports');

drop policy if exists "authenticated delete reports" on storage.objects;
create policy "authenticated delete reports" on storage.objects
  for delete to authenticated using (bucket_id = 'reports');
