import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

import { TECHPRO_LOGO_PNG_BASE64 } from "./report-logo";

export type ReportColumn = { header: string; width: number };
export type ReportResult = { columns: ReportColumn[]; rows: string[][] };

const PAGE_WIDTH = 595.28; // A4 pt
const PAGE_HEIGHT = 841.89;
const MARGIN = 40;
const ROW_HEIGHT = 20;
const HEADER_HEIGHT = 22;
const FONT_SIZE = 9;
const FOOTER_HEIGHT = 28;

const BRAND_RED = rgb(0.82, 0.09, 0.09);
const BRAND_RED_DARK = rgb(0.55, 0.04, 0.04);
const INK = rgb(0.12, 0.12, 0.14);
const MUTED = rgb(0.45, 0.45, 0.48);
const ROW_STRIPE = rgb(0.97, 0.96, 0.96);
const LINE = rgb(0.86, 0.86, 0.87);

function truncateToWidth(text: string, width: number, font: PDFFont, size: number): string {
  if (font.widthOfTextAtSize(text, size) <= width - 8) return text;
  let result = text;
  while (result.length > 1 && font.widthOfTextAtSize(result + "…", size) > width - 8) {
    result = result.slice(0, -1);
  }
  return result + "…";
}

export async function buildTablePdf(opts: {
  title: string;
  subtitle: string;
  columns: ReportColumn[];
  rows: string[][];
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const logoBytes = Uint8Array.from(atob(TECHPRO_LOGO_PNG_BASE64), (c) => c.charCodeAt(0));
  const logo = await doc.embedPng(logoBytes);
  const logoWidth = 84;
  const logoHeight = logo.height * (logoWidth / logo.width);
  const usableWidth = PAGE_WIDTH - MARGIN * 2;

  let page: PDFPage = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;
  let pageNumber = 1;
  const pages: PDFPage[] = [page];

  const drawLetterhead = () => {
    page.drawImage(logo, { x: MARGIN, y: y - logoHeight, width: logoWidth, height: logoHeight });
    const textX = MARGIN + logoWidth + 14;
    page.drawText(opts.title, { x: textX, y: y - 14, size: 15, font: boldFont, color: INK });
    page.drawText(opts.subtitle, { x: textX, y: y - 30, size: 9.5, font, color: MUTED });
    page.drawText("TechPro Inventory Console", { x: textX, y: y - 44, size: 8, font, color: MUTED });
    y -= logoHeight + 8;
    page.drawRectangle({ x: MARGIN, y, width: usableWidth, height: 2.4, color: BRAND_RED });
    y -= 18;
  };

  const drawTableHeader = () => {
    let x = MARGIN;
    page.drawRectangle({
      x: MARGIN,
      y: y - HEADER_HEIGHT,
      width: usableWidth,
      height: HEADER_HEIGHT,
      color: BRAND_RED_DARK,
    });
    for (const col of opts.columns) {
      page.drawText(truncateToWidth(col.header, col.width, boldFont, FONT_SIZE), {
        x: x + 6,
        y: y - HEADER_HEIGHT + 7,
        size: FONT_SIZE,
        font: boldFont,
        color: rgb(1, 1, 1),
      });
      x += col.width;
    }
    y -= HEADER_HEIGHT;
  };

  const drawFooter = (pageIndexLabel: string) => {
    page.drawRectangle({ x: MARGIN, y: FOOTER_HEIGHT - 10, width: usableWidth, height: 0.75, color: LINE });
    page.drawText("Generated by TechPro Inventory Console", {
      x: MARGIN,
      y: FOOTER_HEIGHT - 22,
      size: 7.5,
      font,
      color: MUTED,
    });
    page.drawText(pageIndexLabel, {
      x: MARGIN + usableWidth - font.widthOfTextAtSize(pageIndexLabel, 7.5),
      y: FOOTER_HEIGHT - 22,
      size: 7.5,
      font,
      color: MUTED,
    });
  };

  const newPage = () => {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    pages.push(page);
    pageNumber += 1;
    y = PAGE_HEIGHT - MARGIN;
    drawTableHeader();
  };

  drawLetterhead();
  drawTableHeader();

  if (opts.rows.length === 0) {
    page.drawText("No records found for this period.", {
      x: MARGIN,
      y: y - 16,
      size: 10,
      font,
      color: MUTED,
    });
  }

  opts.rows.forEach((row, rowIndex) => {
    if (y - ROW_HEIGHT < MARGIN + FOOTER_HEIGHT) newPage();
    if (rowIndex % 2 === 1) {
      page.drawRectangle({ x: MARGIN, y: y - ROW_HEIGHT, width: usableWidth, height: ROW_HEIGHT, color: ROW_STRIPE });
    }
    let x = MARGIN;
    for (let i = 0; i < opts.columns.length; i++) {
      const col = opts.columns[i]!;
      page.drawText(truncateToWidth(row[i] ?? "", col.width, font, FONT_SIZE), {
        x: x + 6,
        y: y - ROW_HEIGHT + 6,
        size: FONT_SIZE,
        font,
        color: INK,
      });
      x += col.width;
    }
    y -= ROW_HEIGHT;
    page.drawLine({
      start: { x: MARGIN, y },
      end: { x: MARGIN + usableWidth, y },
      thickness: 0.3,
      color: LINE,
    });
  });

  const total = pages.length;
  pages.forEach((p, i) => {
    page = p;
    drawFooter(`Page ${i + 1} of ${total}`);
  });

  return doc.save();
}
