/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as EssentialReportRouteImport } from './routes/essential-report'
import { Route as FillAmountRouteImport } from './routes/fill-amount'
import { Route as InstallAppRouteImport } from './routes/install-app'
import { Route as InventoryItemsRouteImport } from './routes/inventory-items'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LowStockRouteImport } from './routes/low-stock'
import { Route as MachineHoursRouteImport } from './routes/machine-hours'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as MonthlyExpenseRouteImport } from './routes/monthly-expense'
import { Route as TimelinessConfigurationRouteImport } from './routes/timeliness-configuration'
import { Route as ToolAssignedLogRouteImport } from './routes/tool-assigned-log'
import { Route as ToolStockWithdrawalLogRouteImport } from './routes/tool-stock-withdrawal-log'
import { Route as ToolTypesRouteImport } from './routes/tool-types'
import { Route as ToolsOrderLogRouteImport } from './routes/tools-order-log'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const EssentialReportRoute = EssentialReportRouteImport.update({
  id: '/essential-report',
  path: '/essential-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FillAmountRoute = FillAmountRouteImport.update({
  id: '/fill-amount',
  path: '/fill-amount',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallAppRoute = InstallAppRouteImport.update({
  id: '/install-app',
  path: '/install-app',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory-items',
  path: '/inventory-items',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LowStockRoute = LowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineHoursRoute = MachineHoursRouteImport.update({
  id: '/machine-hours',
  path: '/machine-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyExpenseRoute = MonthlyExpenseRouteImport.update({
  id: '/monthly-expense',
  path: '/monthly-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelinessConfigurationRoute = TimelinessConfigurationRouteImport.update({
  id: '/timeliness-configuration',
  path: '/timeliness-configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolAssignedLogRoute = ToolAssignedLogRouteImport.update({
  id: '/tool-assigned-log',
  path: '/tool-assigned-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolStockWithdrawalLogRoute = ToolStockWithdrawalLogRouteImport.update({
  id: '/tool-stock-withdrawal-log',
  path: '/tool-stock-withdrawal-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolTypesRoute = ToolTypesRouteImport.update({
  id: '/tool-types',
  path: '/tool-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOrderLogRoute = ToolsOrderLogRouteImport.update({
  id: '/tools-order-log',
  path: '/tools-order-log',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/company': typeof CompanyRoute
  '/essential-report': typeof EssentialReportRoute
  '/fill-amount': typeof FillAmountRoute
  '/install-app': typeof InstallAppRoute
  '/inventory-items': typeof InventoryItemsRoute
  '/login': typeof LoginRoute
  '/low-stock': typeof LowStockRoute
  '/machine-hours': typeof MachineHoursRoute
  '/machines': typeof MachinesRoute
  '/monthly-expense': typeof MonthlyExpenseRoute
  '/timeliness-configuration': typeof TimelinessConfigurationRoute
  '/tool-assigned-log': typeof ToolAssignedLogRoute
  '/tool-stock-withdrawal-log': typeof ToolStockWithdrawalLogRoute
  '/tool-types': typeof ToolTypesRoute
  '/tools-order-log': typeof ToolsOrderLogRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/company': typeof CompanyRoute
  '/essential-report': typeof EssentialReportRoute
  '/fill-amount': typeof FillAmountRoute
  '/install-app': typeof InstallAppRoute
  '/inventory-items': typeof InventoryItemsRoute
  '/login': typeof LoginRoute
  '/low-stock': typeof LowStockRoute
  '/machine-hours': typeof MachineHoursRoute
  '/machines': typeof MachinesRoute
  '/monthly-expense': typeof MonthlyExpenseRoute
  '/timeliness-configuration': typeof TimelinessConfigurationRoute
  '/tool-assigned-log': typeof ToolAssignedLogRoute
  '/tool-stock-withdrawal-log': typeof ToolStockWithdrawalLogRoute
  '/tool-types': typeof ToolTypesRoute
  '/tools-order-log': typeof ToolsOrderLogRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/company': typeof CompanyRoute
  '/essential-report': typeof EssentialReportRoute
  '/fill-amount': typeof FillAmountRoute
  '/install-app': typeof InstallAppRoute
  '/inventory-items': typeof InventoryItemsRoute
  '/login': typeof LoginRoute
  '/low-stock': typeof LowStockRoute
  '/machine-hours': typeof MachineHoursRoute
  '/machines': typeof MachinesRoute
  '/monthly-expense': typeof MonthlyExpenseRoute
  '/timeliness-configuration': typeof TimelinessConfigurationRoute
  '/tool-assigned-log': typeof ToolAssignedLogRoute
  '/tool-stock-withdrawal-log': typeof ToolStockWithdrawalLogRoute
  '/tool-types': typeof ToolTypesRoute
  '/tools-order-log': typeof ToolsOrderLogRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/company'
    | '/essential-report'
    | '/fill-amount'
    | '/install-app'
    | '/inventory-items'
    | '/login'
    | '/low-stock'
    | '/machine-hours'
    | '/machines'
    | '/monthly-expense'
    | '/timeliness-configuration'
    | '/tool-assigned-log'
    | '/tool-stock-withdrawal-log'
    | '/tool-types'
    | '/tools-order-log'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/company'
    | '/essential-report'
    | '/fill-amount'
    | '/install-app'
    | '/inventory-items'
    | '/login'
    | '/low-stock'
    | '/machine-hours'
    | '/machines'
    | '/monthly-expense'
    | '/timeliness-configuration'
    | '/tool-assigned-log'
    | '/tool-stock-withdrawal-log'
    | '/tool-types'
    | '/tools-order-log'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/company'
    | '/essential-report'
    | '/fill-amount'
    | '/install-app'
    | '/inventory-items'
    | '/login'
    | '/low-stock'
    | '/machine-hours'
    | '/machines'
    | '/monthly-expense'
    | '/timeliness-configuration'
    | '/tool-assigned-log'
    | '/tool-stock-withdrawal-log'
    | '/tool-types'
    | '/tools-order-log'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  CompanyRoute: typeof CompanyRoute
  EssentialReportRoute: typeof EssentialReportRoute
  FillAmountRoute: typeof FillAmountRoute
  InstallAppRoute: typeof InstallAppRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  LoginRoute: typeof LoginRoute
  LowStockRoute: typeof LowStockRoute
  MachineHoursRoute: typeof MachineHoursRoute
  MachinesRoute: typeof MachinesRoute
  MonthlyExpenseRoute: typeof MonthlyExpenseRoute
  TimelinessConfigurationRoute: typeof TimelinessConfigurationRoute
  ToolAssignedLogRoute: typeof ToolAssignedLogRoute
  ToolStockWithdrawalLogRoute: typeof ToolStockWithdrawalLogRoute
  ToolTypesRoute: typeof ToolTypesRoute
  ToolsOrderLogRoute: typeof ToolsOrderLogRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essential-report': {
      id: '/essential-report'
      path: '/essential-report'
      fullPath: '/essential-report'
      preLoaderRoute: typeof EssentialReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-amount': {
      id: '/fill-amount'
      path: '/fill-amount'
      fullPath: '/fill-amount'
      preLoaderRoute: typeof FillAmountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install-app': {
      id: '/install-app'
      path: '/install-app'
      fullPath: '/install-app'
      preLoaderRoute: typeof InstallAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-items': {
      id: '/inventory-items'
      path: '/inventory-items'
      fullPath: '/inventory-items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/low-stock': {
      id: '/low-stock'
      path: '/low-stock'
      fullPath: '/low-stock'
      preLoaderRoute: typeof LowStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine-hours': {
      id: '/machine-hours'
      path: '/machine-hours'
      fullPath: '/machine-hours'
      preLoaderRoute: typeof MachineHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-expense': {
      id: '/monthly-expense'
      path: '/monthly-expense'
      fullPath: '/monthly-expense'
      preLoaderRoute: typeof MonthlyExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeliness-configuration': {
      id: '/timeliness-configuration'
      path: '/timeliness-configuration'
      fullPath: '/timeliness-configuration'
      preLoaderRoute: typeof TimelinessConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-assigned-log': {
      id: '/tool-assigned-log'
      path: '/tool-assigned-log'
      fullPath: '/tool-assigned-log'
      preLoaderRoute: typeof ToolAssignedLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-stock-withdrawal-log': {
      id: '/tool-stock-withdrawal-log'
      path: '/tool-stock-withdrawal-log'
      fullPath: '/tool-stock-withdrawal-log'
      preLoaderRoute: typeof ToolStockWithdrawalLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-types': {
      id: '/tool-types'
      path: '/tool-types'
      fullPath: '/tool-types'
      preLoaderRoute: typeof ToolTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-order-log': {
      id: '/tools-order-log'
      path: '/tools-order-log'
      fullPath: '/tools-order-log'
      preLoaderRoute: typeof ToolsOrderLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  CompanyRoute: CompanyRoute,
  EssentialReportRoute: EssentialReportRoute,
  FillAmountRoute: FillAmountRoute,
  InstallAppRoute: InstallAppRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  LoginRoute: LoginRoute,
  LowStockRoute: LowStockRoute,
  MachineHoursRoute: MachineHoursRoute,
  MachinesRoute: MachinesRoute,
  MonthlyExpenseRoute: MonthlyExpenseRoute,
  TimelinessConfigurationRoute: TimelinessConfigurationRoute,
  ToolAssignedLogRoute: ToolAssignedLogRoute,
  ToolStockWithdrawalLogRoute: ToolStockWithdrawalLogRoute,
  ToolTypesRoute: ToolTypesRoute,
  ToolsOrderLogRoute: ToolsOrderLogRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
